---
- name: Ensure ssh directories exist
  sudo: yes
  file: path={{item.home}}/.ssh state=directory owner={{item.name}} group={{item.group}}
  with_items: github_users

- name: Inject personal rack enabled key
  sudo: yes
  copy: src={{github_key}} dest={{item.home}}/.ssh/github_rsa force=yes owner={{item.name}} group={{item.group}} mode=0600
  with_items: github_users

- name: Config ssh to use the key for anything within github
  sudo: yes
  template: src=ssh_config dest={{item.home}}/.ssh/config owner={{item.name}} group={{item.group}}
  with_items: github_users
